server {
    listen 80;
    server_name _;

    root /usr/share/nginx/html;
    index index.html;

    # Si le fichier demandé n'existe pas, on retourne l'index.html de React (SPA fallback)
    location / {
        try_files $uri $uri/ /index.html;
    }
}
