version: '3.8'

services:
  db:
    image: postgres:15-alpine
    container_name: mindboard-postgres
    restart: always
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: adminpassword
      POSTGRES_DB: mindboarddb
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: mindboard-backend
    restart: always
    ports:
      - "3000:3000"
    environment:
      - DATABASE_URL=postgresql://admin:adminpassword@db:5432/mindboarddb?schema=public
      - JWT_SECRET=votre_secret_inviolable_pour_les_sessions_1234
      - NODE_ENV=production
    depends_on:
      - db

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
      args:
        # Build argument injecté dynamiquement dans la configuration Vite !
        - VITE_API_URL=https://mindboard.akabia.fr
    container_name: mindboard-frontend
    restart: always
    ports:
      # Port 80 interne de Nginx mappé sur le port 8080 de l'hôte
      - "8080:80"
    depends_on:
      - backend

volumes:
  pgdata:
